/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/nasaUranus.glb --transform 
Files: ./public/nasaUranus.glb [172.65KB] > nasaUranus-transformed.glb [45.73KB] (74%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nasaUranus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Uranus.geometry} material={materials['Default OBJ.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/nasaUranus-transformed.glb')
